[package]
name = "lockstep-cli"
version = "0.1.14"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "lockstep command-line interface."

[[bin]]
name = "lockstep"
path = "src/main.rs"

[dependencies]
lockstep-core = { workspace = true }
lockstep-config = { workspace = true }
lockstep-engine = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
